- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy roboshop config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Clean old App content. Remove the directory if already exists
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

#  Func_print_head "Restart service"
#  systemctl restart nginx &>>$log_file
#  systemctl enable nginx &>>$log_file
#  func_status_check $?
#  Func_print_head "Install nginx"
#  yum install nginx -y &>>$log_file
#  func_status_check $?
#
#  Func_print_head "Copy roboshop config file"
#  cp roboshop.conf /etc/nginx/default.d/roboshop.conf &>>$log_file
#  func_status_check $?
#
#  Func_print_head "Clean old App content"
#  rm -rf /usr/share/nginx/html/* &>>$log_file
#  func_status_check $?
#
#  Func_print_head "Download App content"
#  curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>$log_file
#  func_status_check $?
#
#  Func_print_head "extract App content"
#  cd /usr/share/nginx/html &>>$log_file
#  unzip /tmp/frontend.zip &>>$log_file
#  func_status_check $?
#
#  Func_print_head "Restart service"
#  systemctl restart nginx &>>$log_file
#  systemctl enable nginx &>>$log_file
#  func_status_check $?