#- name: Demo
#  ansible.builtin.debug:
#    msg: Component - Frontend

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy roboshop config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Clean old App content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create App content directory if it doesn't exists
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: extract App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes
- name: start service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enables: true

